[package]
name = "auto_spotify_spotx"
version = "0.1.11"
edition = "2021"

[dependencies]
fluent = "0.16.1"
locale_config = "0.3.0"
reqwest = { version = "0.11.27", features = ["blocking"] }
unic-langid = { version = "0.9.5", features = ["unic-langid-macros"] }
